jenkinsci/script-security-plugin

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
I found that when two or more functional test cases share a single JVM (for example, live in the same suite), static store of `Whitelist.all()` could prevent subsequent tests from running correctly if they made use of `ScriptApproval.approvedSignatures` via `ApprovedWhitelist`.
@reviewbybees
> Whitelist.all() should be scoped per Jenkins instance

- .gitignore
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript/config.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
[JENKINS-25784](https://issues.jenkins-ci.org/browse/JENKINS-25784)
> [JENKINS-25784] Defaulting of sandbox mode based on RUN_SCRIPTS privs

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
> Provide better diagnostics for GroovyObject.invokeMethod

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Taken from [`DockerDSL`](https://github.com/jenkinsci/docker-workflow-plugin/blob/1beac603eea45e8f44479fe992b044ba862b277d/src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java#L53-65).
@reviewbybees
> Some more useful things to whitelist

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Follow-up to #7. @reviewbybees
> [JENKINS-25119] Cleaning up test from #7

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
The code is not clean according to the local FindBugs run
> Enable FindBugs runs on "verify" stages + XML report generation

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Whitelist compareLessThan

- pom.xml
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Also allow Map methods to be called from within sandbox.
Related to https://github.com/jenkinsci/workflow-plugin/pull/131
> Pick up a new version of groovy-sandbox that properly handles Map property access

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest/all.groovy
Simply a mergeable (and passing) version of #17.
@reviewbybees
> [FIXED JENKINS-28154] Confirm fix of problem with operators

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Some comparison operators were missing in the white-list
@reviewbybees
> whilelist more comparison operators

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> whilelist some standard groovy operators

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Add Object getClass and DefaultGroovyMethod plus to whitelist.

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-31234](https://issues.jenkins-ci.org/browse/JENKINS-31234)
@reviewbybees
> [JENKINS-31234] Support Singleton.instance syntax

- pom.xml
Plugin updated and deprecated configuration removed
/cc @jglick
> Findbugs plugin updated

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-31701](https://issues.jenkins-ci.org/browse/JENKINS-31701)
@reviewbybees
> [JENKINS-31701] Misclassification of a method taking long and being passed an int

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-32211](https://issues.jenkins-ci.org/browse/JENKINS-32211)
Add `tokenize` to the whitelist.
@reviewbybees
> [JENKINS-32211] Add `tokenize` to the whitelist.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Expand whitelist, specially with default groovy methods

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/JenkinsWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
Validate content of whitelists and enforce a consistent sort order and uniqueness. Should make it easier to add new entries in parallel PRs while catching common mistakes.
@reviewbybees
> Clean up whitelists

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Subsumes #40.
@reviewbybees esp. @Vlatombe
> Interpret .prop as @Whitelisted public boolean isProp()

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
@reviewbybees 
Related to https://github.com/jenkinsci/parallel-test-executor-plugin/pull/17
> Allow usage of isXXXX method as getter

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Whitelist some string regexp replacement functions and a char replacement function
@reviewbybees
> whitelist some more string functions

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> whitelist locales and locale specific up/lower case

- pom.xml
- src/main/resources/index.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
> [JENKINS-32493] Baseline 1.580.1 and Parent POM 2.3

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-27725](https://issues.jenkins-ci.org/browse/JENKINS-27725) and some related issues, such as handling of virtual fields (which would prevent you from using `Process.text` even if #45 did not blacklist the creation of the `Process`).
@reviewbybees
> [JENKINS-27725] More DefaultGroovyMethods handling

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
> Groovy prefers a getter or setter to a raw field access

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Companion to https://github.com/cloudbees/groovy-cps/pull/21.
@reviewbybees esp. @kohsuke
> [JENKINS-28277] Demonstrating that curry/ncurry work with the sandbox

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
With this fix plus https://github.com/cloudbees/groovy-cps/pull/23, the test in https://github.com/jenkinsci/workflow-plugin/pull/372 still fails, but now for the well-understood JENKINS-27421, just as if the sandbox were disabled.
@reviewbybees esp. @kohsuke
> [JENKINS-26481] DefaultGroovyMethods logic error

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyShellLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyXmlLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/JellyLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/JexlLanguage.java
See [JENKINS-34096](https://issues.jenkins-ci.org/browse/JENKINS-34096)
> [JENKINS-34096] Fix Findbugs issues

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest/all.groovy
> Whitelist some methods to get substrings

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/AbstractApprovalTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/Approvable.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/EntryApprovalTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/Manager.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
See [JENKINS-34251](https://issues.jenkins-ci.org/browse/JENKINS-34251)
Small additions so that for both scripts and classpath entries we have:
* Configure and use with and without security.
* Full cycle of several entities checking from the model and from the UI.
Most of the changes are to factor out the common parts.
@reviewbybees
> [JENKINS-34251] Some additional tests

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
Fixes a mistake in #55.
@reviewbybees and @davidkarlsen
> Forgot to specify FQN

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
#58 follow-up.
@reviewbybees and @magnusr
> [JENKINS-33023] Making sure we can really use enums without extra whitelisting

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
> Better matching of enum initializers

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-34739](https://issues.jenkins-ci.org/browse/JENKINS-34739)
Replaces the fix in #58 (and the follow-up in #65).
@reviewbybees and CC @magnusr
> [JENKINS-34739] Handle varargs

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-35191
cc @reviewbybees @jglick
> [FIXED JENKINS-35191] Add Map.keySet() and Map.value() to whitelist.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-27390
cc @reviewbybees @jglick @kohsuke
> [FIXED JENKINS-27390] Added Number.intValue() and friends.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-32661
cc @reviewbybees @jglick
> [FIXED JENKINS-32661] Add String.substring(int) to whitelist.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-33049
cc @reviewbybees @jglick
> [FIXED JENKINS-33049] Added DGM for leftShift to a String.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-32676
cc @reviewbybees @jglick
> [FIXED JENKINS-32676] Adding DGMs for join and push.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
[JENKINS-37344](https://issues.jenkins-ci.org/browse/JENKINS-37344)
cc @reviewbybees esp @jglick
> [FIXED JENKINS-37344] Add some common Map and Collection methods.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Stuff I found in a user’s script that should not have been there.
@reviewbybees
> Adding some more file-related blacklist entries

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Approving a couple things

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Mentioned in [JENKINS-38352](https://issues.jenkins-ci.org/browse/JENKINS-38352).
@reviewbybees
> Blacklist System.exit

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Allowing things like:
(int) ( System.currentTimeMillis() + 12345 )/1000
> Whitelist casts

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
def someString="1234567890"
echo someString.take(5)
> Whitelist this expression:

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Currently Scripts may catch exceptions, but not fetch their messages for i.e. putting it into error report mails.
> Permit access to the messages of exceptions.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Noticed by @davehunt [here](https://gist.github.com/davehunt/41f22e87c0c50f0b8b39f08d5382a4b1).
@reviewbybees
> Adding some default whitelist entries

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
[JENKINS-38908](https://issues.jenkins-ci.org/browse/JENKINS-38908)
@reviewbybees
> [JENKINS-38908] Varargs bug

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
UI continues that created in #24.
@reviewbybees
> More strenuous blacklisting

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Some assorted whitelist additions

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This PR is suggest by @rsandell [here](https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/22)
> [JENKINS-42091] Add some needed methods of JSON superclass

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Based on the conversation in #87 I've picked out the non-XML items and updated the list to contain them.  It sounded like people were needing some of these items (and I have use for a few of them too).
> Cherry-picked non-XML items from PR #87

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
[JENKINS-41797](https://issues.jenkins-ci.org/browse/JENKINS-41797)
> [FIXED JENKINS-41797] Make sure wrapper WeakHashMap will not be manipulated concurrenlty

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
[JENKINS-40849](https://issues.jenkins-ci.org/browse/JENKINS-40849)
cc @reviewbybees esp @jglick
> [FIXED JENKINS-40849] Add Result.* fields to whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Whitelist String.split()

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Add Integer.valueOf()

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Would like to get these string methods added to the whitelist.
> Add various string methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
see: http://docs.groovy-lang.org/1.8.9/html/api/org/codehaus/groovy/runtime/DefaultGroovyMethods.html#sort(java.util.Collection)
> Add sort method for collections that have comparable items

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
Pending [INFRA-1247](https://issues.jenkins-ci.org/browse/INFRA-1247).
@reviewbybees
> Jenkinsfile and POM updates

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Noticed in [JENKINS-45308](https://issues.jenkins-ci.org/browse/JENKINS-45308) that somebody was trying something which should never be allowed in the sandbox.
@reviewbybees
> Added some static methods returning File to the blacklist

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
#134 pointed to an inconsistency in handling of `Number` receivers.
@reviewbybees
> Cleaning up & clarifying how math operations are processed

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Plus containsAll on collections.
> Add missing whitelist entries for DefaultGroovyMethods sort and contains operations on arrays

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Downstream of https://github.com/jenkinsci/groovy-sandbox/pull/38
> [JENKINS-33468] Enable closure implicit parameter test

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46191](https://issues.jenkins-ci.org/browse/JENKINS-46191)
Mainly here to verify that nothing else is broken by the upstream change in https://github.com/jenkinsci/groovy-sandbox/pull/39, but no harm in duplicating the test from upstream as well.
> [JENKINS-46191] Verify fix from groovy-sandbox

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
[JENKINS-46346](https://issues.jenkins-ci.org/browse/JENKINS-46346)
@reviewbybees, specially @jglick and @abayer
> [JENKINS-46346] Fix failure tests

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46358](https://issues.jenkins-ci.org/browse/JENKINS-46358)
These will be added to CPS in https://github.com/cloudbees/groovy-cps/pull/70
> [JENKINS-46358] Whitelist new StringGroovyMethods

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-44557](https://issues.jenkins-ci.org/browse/JENKINS-44557)
> [FIXED JENKINS-44557] Properly cast GString in vargs.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
[JENKINS-47666](https://issues.jenkins-ci.org/browse/JENKINS-47666)
> [FIXED JENKINS-47666] Add Math.max and Math.min to whitelist

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46757](https://issues.jenkins-ci.org/browse/JENKINS-46757)
@reviewbybees
> [JENKINS-46757] Reproduced in test

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/SystemCommandLanguage.java
> Introduced SystemCommandLanguage

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AclAwareWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
@jglick Some leftovers from #180 - this way I don't have to worry too much about that blocking the original PR if it introduces some contentious point.
> One more optimization and a cleanup change and doc change requested

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
[JENKINS-49542](https://issues.jenkins-ci.org/browse/JENKINS-49542)
> [FIXED JENKINS-49542] Whitelist Map#isEmpty()

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
first: http://docs.groovy-lang.org/latest/html/api/org/codehaus/groovy/runtime/DefaultGroovyMethods.html#first-java.lang.Iterable-
last: http://docs.groovy-lang.org/latest/html/api/org/codehaus/groovy/runtime/DefaultGroovyMethods.html#last-java.lang.Iterable-
> Whitelist DefaultGroovyMethods.first and .last

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
[JENKINS-44924](https://issues.jenkins-ci.org/browse/JENKINS-44924)
Downstream of https://github.com/cloudbees/groovy-cps/pull/86 (for all intents and purposes - it's not *literally* downstream, but...)
> [JENKINS-44924] Whitelist DefaultGroovyMethods for sort, unique, etc

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-50380](https://issues.jenkins-ci.org/browse/JENKINS-50380)
Downstream of https://github.com/jenkinsci/groovy-sandbox/pull/45
> [JENKINS-50380] checkedCast should just return object when assignable

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
I think is a useful method, so you can use code like
```
amethod(url) {
println(url - "file://")
}
```
> Add the ability to use minus method with strings and def

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Please add java.lang.String.indexOf(String, int) to the whitelist
> whitelist java.lang.String.indexOf(String, int)

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
[JENKINS-54614](https://issues.jenkins-ci.org/browse/JENKINS-54614)
> [FIXED JENKINS-54614] Add List#subList to whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
See [JENKINS-55411](https://issues.jenkins-ci.org/browse/JENKINS-55411).
> [FIXED JENKINS-55411] Whitelist DateTimeFormatter.ofPattern(String)

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNoteTest.java
To solve [JENKINS-34973](https://issues.jenkins-ci.org/browse/JENKINS-34973). Includes a more reusable form of https://github.com/jenkinsci/workflow-cps-plugin/pull/205.
> [JENKINS-34973] Register RejectedAccessException at throw time rather than when caught

- pom.xml
https://github.com/jenkinsci/versionnumber-plugin/releases
> update version-number (test) from 1.6 to 1.9

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Handy for scripts like
```groovy
10.times {
// …
}
```
> Whitelist Number.times(Closure)

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Allow some additional String and Base64 related methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
> Allow some Math related methods

- CHANGELOG.md
I am planning on releasing the plugin today.
> Add release notes for 1.76

- .mvn/extensions.xml
- pom.xml
Supercedes #338, #341, and #343. Adapts to jenkinsci/bom#505.
> Update plugin parent POM; use plugin BOM

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript/config.jelly
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNoteTest.java
Matches https://github.com/jenkinsci/jenkins/pull/4365.
> [JEP-223] `RUN_SCRIPTS` → `ADMINISTER`

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelistTest.java
[JENKINS-41797](https://issues.jenkins.io/browse/JENKINS-41797)
* Created a unit test to reproduce the problem
* Fix it with `Collections.synchronizedMap(...)`
> [JENKINS-41797] Resolve infinite loop causes by Concurrent Write to ProxyWhitelist delegates

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Adding all fields and methods from java.time.temporal.ChronoUnit * to the generic whitelist. [Jira Link](https://issues.jenkins.io/browse/JENKINS-66888)
> [JENKINS-66888] Whitelist `java.time.temporal.ChronoUnit.*`

- pom.xml
> Bump parent, baseline, BOM

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
The change whitelists a few signatures listed in [JENKINS-66735](https://issues.jenkins.io/browse/JENKINS-66735)
> JENKINS-66735: Whitelist some common signatures and additional signatures from `CauseOfInterruption`

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
Fixes [JENKINS-67771](https://issues.jenkins.io/browse/JENKINS-67771)
Probably best to merge it after https://github.com/jenkinsci/script-security-plugin/pull/373, because this change either requires 2.319.x or newer.
> Fix broken icon on modern Jenkins versions

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Rather than "master", use "controller"
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
> Make a comment more inclusive

- .github/workflows/cd.yaml
Use Temurin instead of outdated AdoptOpenJDK. setup-java v3 has internal changes only.
---------------
> Switch to Temurin distribution

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/AbstractApprovalTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/EntryApprovalTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/Manager.java
Replaces some constructs with Java 8 features.
------------------------
> Refactoring / modernization

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoaderTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntryTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNoteTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Replacement of some deprecated APIs and migration of `try-fail-catch` based test cases to `assertThrows()`.
---------------------------
> Replace deprecated APIs

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
#463 mixed with 65867aa471265a16198b92fb439782ba3554da66 ⇒ SpotBugs failure
> SpotBugs fix

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
> Add Java 17 to test matrix (owner-filed)

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
Like https://github.com/jenkinsci/workflow-cps-plugin/pull/627 but for the copypasta in `script-security`.
> Reduce reflection in `SecureGroovyScript`

- pom.xml
See https://github.com/jenkinsci/groovy-sandbox/pull/100 and https://github.com/jenkinsci/groovy-sandbox/pull/99.
Tests are upstream, and I don't see any particular reason to duplicate them here.
> Fix interception of return statements in closures in sandboxed Groovy scripts

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AclAwareWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
Replaces the deprecated APIs with their Spring Security based replacements.
--------------------------------------
> Migrate to Spring Security

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/ClassLoaderWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AbstractWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AclAwareWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AnnotatedWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/BlanketWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyShellLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyXmlLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/JellyLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/JexlLanguage.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/SystemCommandLanguage.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder.java
Adds missing nullability annotations.
-----------------------------------------
> Add missing nullability annotations

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
Drops support for OpenJDK versions older than 11.0.17 on the 11 LTS line and 17.0.4 on the 17 LTS line, both now about a year old. The impact when running without these workarounds on older OpenJDK versions is that you may be subject to memory leaks. It seems worth it to simplify this hard-to-maintain reflection-based code and drop support for these older runtime environments. See also https://github.com/jenkinsci/jenkins/pull/8193 and https://github.com/jenkinsci/workflow-cps-plugin/pull/756.
> Remove unnecessary workarounds

- pom.xml
Prompted by https://github.com/jenkinsci/azure-container-agents-plugin/pull/246
I assume due to old bom version? bit unsure why it's clashing
```
[ERROR] Rule 5: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps failed with message:
[ERROR] Failed while enforcing RequireUpperBoundDeps. The error(s) are [
[ERROR] Require upper bound dependencies error for io.jenkins.plugins:caffeine-api:3.1.6-115.vb_8b_b_328e59d8 paths to dependency are:
[ERROR] +-org.jenkins-ci.plugins:azure-container-agents:310.v0fccd2e3ec40
[ERROR]   +-org.jenkins-ci.plugins:azure-credentials:292.v99b_c3eb_4fb_64
[ERROR]     +-io.jenkins.plugins:caffeine-api:3.1.6-115.vb_8b_b_328e59d8 (managed) <-- io.jenkins.plugins:caffeine-api:3.1.8-133.v17b_1ff2e0599
[ERROR] and
[ERROR] …
```
> Bump bom and baseline

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
Update the icon of the "In-process Script Approval" menu under "Manage Jenkins".
The idea is to harmonize the look and feel of the page since most other plugins and especially the core functions there also use these kind of icons.
I opted with built-in icons from [Jenkins core](https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols) to not introduce any new dependencies.
Manual starting local instance, comparing results.
**Before**
**After**
```[tasklist]
```
> Update ScriptApprovalLink icon

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
Fix typo in script security plugin UI.
None.
```[tasklist]
```
> Remove word duplication from Script Security UI

- Jenkinsfile
https://github.com/jenkins-infra/helpdesk/issues/3931#issuecomment-1929457197
> Restore Windows branch in PRs

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
useful when you need the Jenkins version in a pipeline (e.g. to obtain a corresponing agent image for k8s plugin)
```[tasklist]
```
> Whitelist `jenkins.model.Jenkins.VERSION`
