jenkinsci/script-security-plugin

- pom.xml
Otherwise Maven builds started failing recently:
Could not resolve dependencies for project org.jenkins-ci.plugins:script-security:hpi:1.14-SNAPSHOT: Could not find artifact com.github.jnr:jffi:jar:native:1.2.8-20150130.202743-5 in …
Older versions of core bundle a version of JNR that includes a range dependency on `jffi`, which causes failures on projects using a transitive dependency when new snapshot versions are deployed inside the range. This patch just pins the version to that which 1.509.4 actually bundles.
Simply upgrading the core dep would be easier, but that would also prevent updates from being used from `groovy-postbuild`, at least until _that_ plugin gets a newer core dep. Similarly for other plugins which might be using `script-security` in the near future.
@reviewbybees …
> Pin the jffi version as 1.2.7.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Whitelist some more prototypes I run into.
> More generic methods whitelisted

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Sorry for my late work.
This is a test for [JENKINS-25119](https://issues.jenkins-ci.org/browse/JENKINS-25119) fixed in 52d83beb4227416c1fa14e20099ff75400fb6a63, script-security-1.11.
This test fails in script-security <= 1.10 as following:
```
-------------------------------------------------------------------------------
Test set: org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptorTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.266 sec <<< FAILURE!
groovyExtendedMethod(org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptorTest)  Time elapsed: 1.11 sec  <<< FAILURE!
java.lang.AssertionError: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessExc …
```
> [JENKINS-25119] a test for additional methods in the Groovy environment

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
The groovy runtime would resolve a call to a GroovyDefaultMethods method in this case, but the script-security check incorrectly concludes that the call would resolve to the invokeMethod method.
> Fixed incorrect sandbox check when invoking GDM method on a class that defines invokeMethod.

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-29541](https://issues.jenkins-ci.org/browse/JENKINS-29541)
Adding a whitelist entry for `String.substring` is trivial and in fact an administrator could do so for themselves. The bigger problem was with `GString`, whose `invokeMethod` is a little hack to delegate unknown methods to `String`; this needs special treatment. (Ideally the Groovy sandbox library would handle this sort of painful detail, but it does not.)
@reviewbybees
> [JENKINS-29541] GString receiver handling

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/RejectedAccessException.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
In [JENKINS-30432](https://issues.jenkins-ci.org/browse/JENKINS-30432) for example, the user naïvely approved a signature that should never be approved. I have also seen @rsandell accidentally approve usage of `File` methods, which is even more dangerous. Introducing a blacklist of signatures known to be exploitable, or which would have no legitimate use, and sternly warning the administrator not to accept them.
@reviewbybees
> [JENKINS-30432] Warn about dangerous signatures

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
HtmlUnit was recently updated, causing certain tests that used methods in the old version of HtmlUnit to fail.  For now, we're going to skip these tests, test manually, and update the tests after the release of the next core.
> Ignore tests using old HtmlUnit methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Whitelist JsonSlurper and JsonOutput, the JSON parser and formatter recommended by http://www.groovy-lang.org/json.html
> Whitelist JsonSlurper and JsonOutput

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/RejectedAccessException.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/languages/GroovyLanguage.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
After https://github.com/jenkinsci/groovy-postbuild-plugin/pull/24 the oldest baseline used by any plugin depending on this one is 1.580.x (`parallel-test-executor`), followed by 1.596.x (`docker-workflow`); the rest are on 1.609.x.
(As a maintainer of both of those I am tempted to just bump them up too, but that can wait.)
@reviewbybees
> Updated baseline to 1.580.1

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
It's nice to be able to get values when iterating over map entries (otherwise all you can do is get known key values out). 
@reviewbybees
> Add Entry getKey/getValue for java.util.Map

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Sometimes people will try to run, e.g.,
```groovy
def result = 'curl http://server/api'.execute().text
```
which is inherently unsafe.
@reviewbybees
> Blacklist methods which start local processes

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
This is a demonstration for [JENKINS-24399] (https://issues.jenkins-ci.org/browse/JENKINS-24399) Modifying files in class directories can bypass approval in script-security (or class directories are accepted as classpaths).
Do not merge.
script-security 1.5 allows to use a class directory as an additional classpath.
This test shows that users can use class directories whose contents are modified without administrators' approval.
> [JENKINS-24399] A test to reproduce JENKINS-24399

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntryTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
See [JENKINS-24399](https://issues.jenkins-ci.org/browse/JENKINS-24399).
Proposed solution after the discussion in the issue is removing the possibility of using class folder as classpath entries.
Includes https://github.com/jenkinsci/script-security-plugin/pull/4
@reviewbybees
> [JENKINS-24399] Don't allow class directories any more.

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Found that a trick used to bind synthetic methods to existing classes was being rejected by the sandbox. Here it is assumed that the closure itself is implicitly whitelisted; `Whitelist` does not have any mechanism for listing non-Java “methods” like this.
@reviewbybees esp. @kohsuke
> MetaClass delegate handling

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Saw someone trying to use this from a `Jenkinsfile`. It is dangerous, and usually better done with `readFile`.
The constructor overload taking `File` is not a thread because we are already blacklisting the `File` constructors.
@reviewbybees
> Blacklist new java.io.FileInputStream java.lang.String

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Whitelist staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toList variants since they are very useful and harmless
> allow toList methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
`echo env['BUILD_NUMBER']` is broken.
Using `env.BUILD_NUMBER` still works, but both should be accessible.
> Add getAt java.lang.Object java.lang.String

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist-groovy2
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/JenkinsWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/AbstractApprovalTest.java
When building against Jenkins 2.0 Groovy 2.4.6 is used instead of 1.8.9 in the baseline. This brings a couple of issues:
* For some methods in the whitelist there are additional overloads for more specific type arguments, generating approval errors.
* The behavior for ambiguous overloading has changed: no longer "some" version of the method is picked but an exception is thrown.
Besides, the PR includes:
* Findbugs fixes when building against 2.0
* Some cleanup after https://github.com/jenkinsci/script-security-plugin/pull/53
@reviewbybees
> [JENKINS-34466] Fix PCT against 2.0

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-34741](https://issues.jenkins-ci.org/browse/JENKINS-34741)
@oleg-nenashev passed on a report of this. Not yet obvious to me how to fix, but useful to have the test case recorded.
@reviewbybees
> [JENKINS-34741] Reproduced problem in test

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
`currentBuild.rawBuild` is not in and of itself a risk in a Pipeline script, but pretty much anything you would do with the result would be, so best to nip this in the bud.
@reviewbybees
> Blacklisting RunWrapper.getRawBuild

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
Works around [JENKINS-23784](https://issues.jenkins-ci.org/browse/JENKINS-23784) as well as the general expense of calling into core/plugin class loaders repeatedly during Groovy compilation.
@reviewbybees
> [JENKINS-23784] Cache upstream class loader results

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntryTest.java
[JENKINS-37599](https://issues.jenkins-ci.org/browse/JENKINS-37599)
At least makes the problem clearer.
@reviewbybees
> [JENKINS-37599] Prevent empty classpath entries from being saved accidentally

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
These are useful for writing methods/functions that want to check input.
They can also be useful for providing folder-scoped "global" libraries since those must pass security restricitons.
----
After making this change it made me wonder, does the `script-security-plugin` care about language version? There are also some Java 8 methods (since we run Jenkins on Java 8) that would be very useful for us to generically whitelist in this plugin.
> Whitelist Objects.requireNonNull methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
I see that `java.util.Collection.size()` is whitelisted, so presumably it would also be OK to whitelist `java.util.Map.size()`?
Motivation is to enable check for empty Map...
Calling `java.util.Map.size()` does _not_ make it appear in the script approvals, so I did not find a workaround...
I guess the more groovy way is to just do `if (mymap)` instead of `if (mymap.size()>0)` - but getting the number of items in a map seems like a valid thing to do...
Or am I missing something obvious here?`
> Allow java.util.Map.size()

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
We're using the BUILD_TAG to get unique but trackable and predictable names for our docker tags during some CI processes.
Unfortunately this results in a %25 (/) in being presented when there is a branch with '/' in the name (via the bitbucket source plugin which puts branches in folders of repos in folders of projects), which is of course invalid as a docker tag character... and we have bumped into similar ones too
It'd be very useful when processing much of this stuff to be able to encode and decode between string and html encoding form without having to manually whitelist the method.
Could the methods please be added to the generic whitelist
> Add HTML encoding/decoding of strings to whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Add String.find to the generic whitelist since matches is whitelisted and it is literally the same
> Added GroovyStringMethods.find to Whitelist

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
[JENKINS-39159](https://issues.jenkins-ci.org/browse/JENKINS-39159)
@reviewbybees
> [JENKINS-39159] If we create a URLClassLoader we should also close it

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
If you pass null, the code will eventually blow up with NPE (fast for sandbox, during the execution for !sandbox).
Better to annotate it explicitly
@reviewbybees
> Annotate the SecureGroovyScript#script field as Nonnull

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Used by, for example: `'foobar'[0]`
https://issues.jenkins-ci.org/browse/JENKINS-42618
> [FIX JENKINS-42618] Add generic whitelist entry for String.getAt(int).

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
To allow that kind of deduplication (found `.unique()` in the meantime, but I think this method should be still be allowed, as this seems harmless)
```groovy
def variable = ['a', 'b', 'a']
variable = variable.toSet().toList()
```
@reviewbybees
> Allow toList() returning a Collection

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-34741](https://issues.jenkins-ci.org/browse/JENKINS-34741)
Adds logic derived from Groovy's MetaClassImpl#invokeConstructor
method to return the no-parameters constructor when no matching
declared constructor is found, there's one argument, and that one
argument is a Map.
> [FIXED JENKINS-34741] Allow new Class(foo: bar) to work.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist-groovy2
Might be better organized, might be things here that are problems. `invokeMethod` was needed for `sum`, so I've removed `sum` from the tests I'll be pushing up over in `workflow-cps` in an hour or so.
> Adding whitelist methods needed for DefaultGroovyMethods

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/UnapprovedClasspathException.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
This is what plugin used to say before: `UnapprovedClasspathException: classpath entry file:/var/lib/jenkins/scripts/ (25b1d05c615f6e2ce3995a56287bc47e1f4597a4) not yet approved for use`. Confused me for hours as there was no approval request generated contrary what the message implies.
> Be explicit about classpath dir rejection reason

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This enables Jenkinsfile scripts to use .capitalize() for String.
> Add String.capitalize() to whitelist

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
[JENKINS-45117](https://issues.jenkins-ci.org/browse/JENKINS-45117)
@reviewbybees
> [JENKINS-45117] Apply specificity comparisons to constructors, not just methods

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-37129](https://issues.jenkins-ci.org/browse/JENKINS-37129)
As an user, I don't always precisely remember what methods an object has, an I often end up making mistakes. From workflow-cps perspective, this results in trying to call a method that does not exist.
This must result in `MethodMissingException`, just like normal Groovy interpreter. The code currently makes this a `RejectedAccessException`, making the user believe that the method exists but the access it not allowed.
> [JENKINS-37129] unclassified method vs MethodMissingException

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelistTest.java
[JENKINS-34599](https://issues.jenkins-ci.org/browse/JENKINS-34599)
Downstream of https://github.com/kohsuke/groovy-sandbox/pull/33.
@reviewbybees
> [JENKINS-34599] Setting of final fields

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46088](https://issues.jenkins-ci.org/browse/JENKINS-46088)
Downstream of https://github.com/jenkinsci/groovy-sandbox/pull/37
cc @reviewbybees @svanoort
> [JENKINS-46088] Verify removal of double transform of cast expression

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
Also make the test better show out of order issues with the whitelist.  This allows the easiest way to make a string from an array or collection in Groovy. 
@reviewbybees
> Allow string join

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46391](https://issues.jenkins-ci.org/browse/JENKINS-46391)
CPS code ends up calling `~/foo/` as `ScriptBytecodeAdapter.bitwiseNegate(Object)`, so we need to whitelist that. Through whacky Groovy magic, that'll end up resulting in a call behind the scenes to `StringGroovyMethods.bitwiseNegate(CharSequence)`, which returns... a `Pattern`. Because of course it does. So tada.
Also whitelisted `Pattern.compile(String)` and `Pattern#matcher(CharSequence)` since they seem worth whitelisting while we're doing `Pattern`-related stuff.
> [FIXED JENKINS-46391] Fix ~/foo/ and whitelist other Pattern stuff

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-35294](https://issues.jenkins-ci.org/browse/JENKINS-35294)
The examples in the JIRA don't work because of the trailing comma - that's not valid Groovy syntax in the first place.
> [JENKINS-35294] Test verifying enums with varargs work

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
`public Object get(Object key, Object defaultValue)` is a useful Map method, so much so it should be default white listed.
> Whitelist Map's get method

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyMemoryLeakTest.java
[JENKINS-47758](https://issues.jenkins-ci.org/browse/JENKINS-47758)
Snapshot deployed as 1.35-20171101.213128-3 for testing
> [JENKINS-47758] Script security provides automatic memory leak protection to many groovy scripts

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyMemoryLeakTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder.java
Simplification of #161. Yes I checked that the test still fails if
```java
canDoCleanup = true;
```
is commented out.
@reviewbybees
> Removing test dependency on GroovyPostbuildRecorder

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Makes this plugin behave like more of a pure library when it is not in active use: there is no particular reason to even see this management link if all attempted uses of script security (if any) have been successful uses of default whitelist entries in the sandbox.
@reviewbybees
> Hide link to /scriptApproval when there is nothing approved or pending

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-47893](https://issues.jenkins-ci.org/browse/JENKINS-47893)
https://github.com/jenkinsci/script-security-plugin/commit/8abef0d66fa78f4c187789d8fb76680b91ff0e97 fixed GString varargs logic...sort of. For some reason, I put a 0 in for the start index for the array in the parameters, which was wrong. Duh. This fixes that by properly using the right index.
> [FIXED JENKINS-47893] Properly set index for varargs casting

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
[JENKINS-47159](https://issues.jenkins-ci.org/browse/JENKINS-47159)
Replaces #155 
We shouldn't be starting looking for vargs until we've got to the
index of the last parameter type *and* that last parameter type is an
array. So...tada.
cc @reviewbybees @antweiss
> [FIXED JENKINS-47159] Set proper vargs location

- pom.xml
plugin POM 3.0 defaults `java.level` to 8, which is not the right value when we're still building against core 2.7.3. So let's set the level to 7.
> Set java.level to 7

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Noticed this whitelisted in someone’s `scriptApproval.xml`. No idea why, but cannot be a good idea.
@reviewbybees
> Blacklist System.setProperty

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-48501](https://issues.jenkins-ci.org/browse/JENKINS-48501)
Added some more null checks in the vicinity just to be safe, but the
main thing here is that we needed to avoid an NPE *and* treat a null
arg as if it were of the target method's trailing array parameter's
component type, since, well, null is every type.
Downstream test of the specific issue that uncovered this (variable declaration with a specified type in a CPS script without a right-hand side) coming momentarily.
cc @reviewbybees @rsandell
> [FIXED JENKINS-48501] Null-safety in varargs->array check

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
CC @svanoort since I saw you were the most recent person to merge/approve an update to the whitelist.
> add DefaultGroovyMethods contains java.lang.Iterable java.lang.Object to whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
- preventively blacklist System.nanoTime()
- currently the accuracy / precision of the system calls inside a sandbox is very bad and so prevent naturally the attack.
- at this moment, no Spectre/Meltdown attack is possible using groovy sandbox
Compared to the script console, the granularity is 1000x for the sandbox version.
[SECURITY-683](https://issues.jenkins-ci.org/browse/SECURITY-683) (CERT team access only)
@reviewbybees @jglick
> [SECURITY-683] Preventively reduce Spectre/Meltdown risk

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Integer.toString(int, int):
"Returns a string representation of the first argument in the radix specified by the second argument."
see: https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#toString-int-int-
> add Integer.toString(int, int) to generic-whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
http://docs.groovy-lang.org/latest/html/groovy-jdk/java/io/Reader.html#splitEachLine(java.lang.String,%20groovy.lang.Closure)
Per @jglick
> For simple missing entries in the default whitelist I do not bother with JIRA—just file PRs.
Otherwise we are getting `org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods splitEachLine java.lang.String java.lang.String groovy.lang.Closure` with  script-security-plugin 1.33
> Add Reader.splitEachLine

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
* `Objects.hash` Added in Java 7: https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hash(java.lang.Object...)
> Whitelist Objects.hash and Object.hashCode

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
-----
useful for batching up things, like for limiting `parallel` blocks
> Add `DefaultGroovyMethods.collate` variants to whitelist

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
Not a *ton* more helpful, but I think it's better than just "unclassified ...".
I've seen enough cases of people (including myself) getting confused by what "unclassified ..." means that it feels like explaining that it means we couldn't find that particular field/constructor/method/etc is better than being vague. That said, I know it's not *quite* right in all cases, so I need to think on it more.
> Replace "unclassified ..." error messages with something more helpful

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-50470](https://issues.jenkins-ci.org/browse/JENKINS-50470)
See upstream PR at https://github.com/jenkinsci/groovy-sandbox/pull/46, but the gist is that Groovy's normal behavior for this is to treat it the same as we do spread cases - iterate over the list to get the value from each object in the list and return the resulting list.
> [FIXED JENKINS-50470] Treat someList.someField as spread.

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
The sandbox rejects valid Groovy code when trying to call a Closure element of a Map as if it were one of the Map's methods. See [JENKINS-50843](https://issues.jenkins-ci.org/browse/JENKINS-50843).
> Allow calling Closure elements of Maps as methods

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
[JENKINS-46757](https://issues.jenkins-ci.org/browse/JENKINS-46757)
This was actually fixed in JENKINS-50380, in release 1.43.
> [JENKINS-46757] Turn on now-working test.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Push and other members of java.util.List are part of the whitelist, appears that pop() was overlooked when they were added.
> Add java.util.List.pop to the whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Correct me if I'm wrong, but these can probably be allowed. Since they're also allowed for other Collections.
> Added DefaultGroovymethods array methods to whitelist

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
Appears in Sentry logs for Evergreen. While something is very likely wrong in this circumstance, it is not necessarily a software issue, so it is not generally an actionable warning for developers.
> Downgrade warning about pathologically slow load times

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
[JENKINS-53240](https://issues.jenkins-ci.org/browse/JENKINS-53420)
Logic here now is derived from `CpsScript#invokeMethod`.
Downstream validation of the fix coming in a PR to workflow-cps momentarily.
> [FIXED JENKINS-53240] Check for variable in binding first.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
These are quite useful to calculate daily timestamps...
(Currently only Local* and no Zoned*, since I didn't require anything else...)
PS: It looks like the code understands wildcards in signatures, which would have been quite useful here, but the test suite denies me their use... Is this deliberate?
> Whitelist a useful subset of the Java 8 time API

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Try executing this anywhere in Jenkins pipeline code:
```groovy
'42'.asBoolean()
```
Stacktrace:
```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods asBoolean java.lang.CharSequence
at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectStaticMethod(StaticWhitelist.java:189)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:114)
at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
at …
```
> Add asBoolean to the generic whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
I discovered this by attempting a lazy string as a default parameter value in a Jenkins declarative pipeline script.
```groovy
string(name: 'A', defaultValue: 'defaultA', description: '')
string(name: 'B', defaultValue: 'defaultB', description: '')
string(name: 'BUILD_URL', defaultValue: "https://example.com/example_path-${ a -> a << params.A }-${ b -> b << params.B }.tar", description: '')
```
Which led to this stacktrace:
```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.io.Writer java.lang.Object
at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectStaticMethod(StaticWhitelist.java:189)
at …
```
> Add leftShift from java.io.Writer to the whitelist

- .gitignore
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
* isinstance check
* java.lang.Throwable.getCause()
* java.util.Arrays.asList()
* java.util.regex.MatchResult.group(String)
* List - List
> JENKINS-53800: Whitelisting misc. methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This makes it easier to write idiomatic groovy code without whitelisting every list/set operation 😉
Theses should be all public plus/minus methods for current Groovy trunk
> Add missing DefaultGroovyMethods minus/plus whitelist entries

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyMemoryLeakTest.java
[JENKINS-55303](https://issues.jenkins-ci.org/browse/JENKINS-55303)
Based on recommendation by @dwnusbaum to prevent false negative on tests on Java9+.
@jenkinsci/java11-support
> [JENKINS-55303] Skip Memory test on JVM greater than Java 8

- pom.xml
This is a followup for #238 in order to fix master branch.
Thank you @batmat for finding the reason behind this problem.
> Workaround Javadoc issue on JDK 11.0.2

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
These methods are needed for general usage and scripting.
They are easily emulated with the already approved
methods containsKey and get.
> [JENKINS-56688] Add missing Map utility methods.

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
There is never a valid reason for calling `System.exit(1)` in a
Jenkins Groovy script. Ever. So let's just permanently hack it into
always being rejected. Also, let's special case it in `ScriptApproval`
to not even show up as a pending signature.
> Always reject System.exit.

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
```
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods drop java.lang.Iterable int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods drop java.util.List int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods dropRight java.lang.Iterable int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods dropRight java.util.List int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods take java.util.List int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods takeRight java.lang.Iterable int
staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods takeRight java.util.List int
```
> [JENKINS-57299] Whitelist the following variants of drop* and take*:

- pom.xml
Fix the errors noticed in https://github.com/jenkinsci/script-security-plugin/pull/247. Explanation of the root cause is in https://github.com/jenkinsci/plugin-pom/pull/196.
> Update parent pom to fix Javadoc errors on Java 11

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyMemoryLeakTest.java
Tracked down a memory leak in `SandboxResolvingClassLoader.parentClassCache`. Turns out its use of `weakKeys` did not work at all. The existing test did not catch this, since the `parentLoader` in that case is an `UberClassLoader`, which you would not expect to be collected anyway. But if you have a nonempty `SecureGroovyScript.classpath`, for example, then the parent loader was a new `URLClassLoader`, and this never got released. Thus any classes actually loaded from a classpath JAR would never be released, leading to increased heap/metaspace on each build.
(Not sure if there is a case where this could affect Pipeline; the observed case involved the `uno-choice` plugin and build parameters on a freestyle project. https://github.com/jenkinsci/jenkins/pull/4035 also came out of this case; …
> SandboxResolvingClassLoader.parentClassCache could leak loaders

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyMemoryLeakTest.java
#238 is redundant after https://github.com/jenkinsci/jenkins-test-harness/pull/126.
> Java level assumption is now built in to MemoryAssert

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyLanguageCoverageTest.java
With some of the regressions recently, we probably would have caught them if we'd had better coverage of the language as a whole. So, let's add more coverage. This has already uncovered one bug, [JENKINS-46327](https://issues.jenkins-ci.org/browse/JENKINS-46327), and at least one fairly simple operator call that needed a whitelisting (`3.0 * 5.0`). More to come...
> Increasing test coverage of Groovy syntax

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This PR whitelists a few java.io reader and writer methods that are useful on filters (wrapper readers and writers). It also whitelists a few list operations
> JENKINS-57344: Whitelist requests for some java.io and other misc calls

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This PR whitelists mainly a few collection methods that will enable access using range. It also includes a few Groovy collection enhancements in the list.
> JENKINS-58799: Whitelisting a few collection related methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Like for `each`, `any` and `every` might receive a `java.lang.Object` although the object itself is in fact iterable.
Minified example:
```groovy
'string'.split().every { it }
```
-----
I'm not sure if this introduces any security-risks, and if there is a way to verify this. Should there be anything else necessary (like tests), please let me know!
> Update whitelist DefaultGroovyMethods {any, every}

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This adds a variety of java.lang.String methods from StringGroovyMethods to match the CharSequence versions.
This also adds readLines as an acceptable method.
> JENKINS-58894 Add String signatures to match CharSequence counterparts

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This splits out the request to add the readlines methods to the whitelist as requested in #262
> Add readlines to string methods whitelist

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoaderTest.java
See [JENKINS-59587](https://issues.jenkins-ci.org/browse/JENKINS-59587).
While investigating a user-reported performance issue, I noticed among other things that their Pipelines were spending a ton of time blocked waiting to acquire the lock for `PluginManager$UberClassLoader` while loading classes in `SandboxResolvingClassLoader`. This was a little surprising, because this user has a single shared library that is used by all of their Pipeline builds, so I would've thought that they would have a very high cache hit ratio, but that did not seem to be the case.
Looking into it, I noticed that in `SandboxResolvingClassLoader`, we were using `weakValues` on `parentClassCache` itself as of #252. This didn't make sense to me, because the values of `parentClassCache` are `Cache<String, …
> [JENKINS-59587] Use weakValues on the inner caches in SandboxResolvingClassLoader.parentClassCache instead of on the outer cache

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Not sure if it works in CPS-transformed Pipeline code. I tried to use `.toList.subList(…)` as a workaround, but that did not suffice either: I got `java.io.NotSerializableException: java.util.ArrayList$SubList`. Gave up and used something simpler.
> Whitelist entry for Object[].getAt(IntRange)

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This change ensures that all the methods from java.util.regex package are whitelisted. There is no functionality in this package that touches external resources, so everything should be safe to be whitelisted.
> JENKINS-59952: Whitelisting all remaining java.util.regex methods

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
#249 and #261 had some problems. `NumberRange` does not exist in Groovy 2.4.x, which is what Jenkins is using, the `DefaultGroovyMethods.minus` entries are malformed because of `removeAt` and `removeLast`, and `Flushable` is in the `java.io` package, not `java.lang`.
CC @haridsv
> Remove useless whitelist entries, fix typo, and improve tests

- CHANGELOG.md
- README.md
- pom.xml
Load documentation from Github instead of confluence.
Related tickets:
https://issues.jenkins-ci.org/browse/WEBSITE-406
https://issues.jenkins-ci.org/browse/JENKINS-59172
> Load documentation from Github instead of confluence

- CHANGELOG.md
Also adds entries for 1.66 and 1.65 that were accidentally
missed in the migration from the wiki.
I am planning on doing a release today.
> Update changelog for 1.67 release

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Please add to whitelist static method to parse hex.
For example:
`Integer.parseInt("FF", 16)`
> Adding support parse HEX

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Given DayOfWeek getters on date and time classes are whitelisted it makes sense to also whitelist the enum values they return.
> Add Java Time DayOfWeek enum to whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
We currently only have Collections.sort whiltelisted, but every method in this class is a static utility method that is safe, so this PR whitelists all of them. This also whitelists a couple of Throwable.printStackTrace variations. PR #249 already whitelisted a few java.io methods to make it possible to write to a StringWriter, so together this will make it possible to log more detailed error messages that include exception stacktraces and make it easier to troubleshoot some issues.
> JENKINS-60210: Whitelisting all java.util.Collections methods

- CHANGELOG.md
I am planning on releasing the plugin today. I also reformatted the release dates while I was here.
> Add changelog entries for 1.68 and 1.69

- CHANGELOG.md
1.70 went out as part of [today's security advisory](https://jenkins.io/security/advisory/2020-03-09/#SECURITY-1754).
> Add changelog for 1.70

- CHANGELOG.md
In #287 I only added an entry for the most recent security fix, but I used the wrong version. This PR fixes the version, and adds the real entry for 1.70, which was not documented here.
> Move 1.70 changelog entry to 1.71 and add correct entry for 1.70

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelistTest.java
While investigating something else, I noticed that `ProxyWhitelist.reset` didn't clear out static field  signatures when clearing out other types of signatures.
> Clear static field signatures in ProxyWhitelist.reset

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
See [JENKINS-61952](https://issues.jenkins-ci.org/browse/JENKINS-61952).
https://github.com/jenkinsci/script-security-plugin/pull/274 (CC @haridsv) accidentally removed two methods from the whitelist:
* method java.util.regex.Matcher find
* method java.util.regex.Matcher group java.lang.String
This PR adds those methods back to the whitelist. There were also three remaining `java.util.regex.Matcher` methods that were not whitelisted, so this PR also adds those methods to the whitelist:
* method java.util.regex.Matcher end java.lang.String
* method java.util.regex.Matcher find int
* method java.util.regex.Matcher start java.lang.String
> [JENKINS-61952] Add remaining methods on java.util.regex.Matcher to the whitelist

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
Subsumes #257. Should fix enforcer errors seen in the CI builds when testing against 2.222.x.
2.176.x is the fourth-oldest LTS line at this point, so it seems like a conservative enough upgrade. The core BOM used by version 4.x of the parent POM also supports 2.164.3 if we want to be even more conservative.
> Fix build errors by updating minimum core version and parent POM

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
Same as #276 . It's been 5 months since last reply. 
Only add `Serializable`. This will make plugins like active-choices-plugin compatible to pipeline script.
> implementing serializable in SecureGroovyScript & ClasspathEntry

- pom.xml
The reason for the update is just that security scanners are complaining about https://github.com/ben-manes/caffeine/issues/301. As far as I can tell there is no actual issue because the library author verified that the build was reproducible.
Release notes for the library can be found [here](https://github.com/ben-manes/caffeine/releases).
> Update caffeine to 2.8.2

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Refiling #272 with two changes:
* I removed methods whose parameters include `FieldPosition` and `ParsePosition` because the constructors and methods for those types are not whitelisted, so they could not actually be used (I don't think the types are unsafe, but don't really want to add them unless they are being used).
* I added methods methods that are overridden by `DateFormat` but defined in `Format`. In the original PR these had been accidentally added to the whitelist using `DateFormat` as the receiver so they caused build failures and were removed, but I think it makes sense to go ahead and whitelist them, we just need to use `Format` as the receiver.
CC @cidermole
> Add most Calendar, DateFormat, and Format members to generic whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Refiling #273 but with `ScriptBytecodeAdapter.unaryMinus` and `unaryPlus` removed because  those methods use reflection on non-numeric types to invoke methods that may not be whitelisted.
CC @basil
> Add various methods to whitelist

- Jenkinsfile
#293 fixed the build after it was broken by jenkins-infra/pipeline-library#92, but then jenkins-infra/pipeline-library#146 broke it again.
This PR stops using `buildPlugin.recommendedConfigurations` to avoid these kinds of issues in the first place.
> Replace use of recommendedPlugins with explicit configurations in Jenkinsfile

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
https://github.com/jenkinsci/jenkins/pull/4546 in Jenkins 2.226+ improves the layout of the "Manage Jenkins" page by categorizing the links. We should go ahead and implement `getCategoryName` even without updating the minimum core version here so that the "In-process Script Approval" link shows up in the security category in newer versions of Jenkins instead of being uncategorized.
> Add category to In-process Script Approval management link

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
Adds three result color related methods to the Jenkins whitelist. I took a quick look at these methods and they seemed safe to me; however, I do not have a full understanding of how to evaluate safety, so if these methods are unsafe I would appreciate an explanation as to why.
For background, I use these methods in my pipelines as follows:
```groovy
/**
* Return a Slack color from a given Jenkins result.
*
* @param resultStr The Jenkins job result, as returned by {@link RunWrapper#getResult()}. Typically
* this is the value of {@code currentBuild.result}.
* @return A valid Slack color. This is typically one of the predefined Slack colors or otherwise
* the value of {@link BallColor#getHtmlBaseColor()}.
*/
def getSlackColor(String resultStr) {
Result result = Result.fromString(resultStr) …
```
> Add result color related methods to Jenkins whitelist

- CHANGELOG.md
I am planning on releasing the plugin today.
I also replaced generic use of the terms `whitelist` and `blacklist` in the changelog with `list of approved signatures` and `list of dangerous signatures`, which are the terms that are used in the UI. I did not modify references that were talking about specific classes such as `AbstractWhitelist`.
> Add release notes for 2.73 and 2.74

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
https://issues.jenkins-ci.org/browse/JENKINS-63171
> [JENKINS-63171] Add more generic whitelist entries

- CHANGELOG.md
See https://jenkins.io/security/advisory/2020-09-23/#SECURITY-2020.
> Add release notes for 1.75

- Jenkinsfile
#306 (which is just changelog updates) was failing in the Java 11 branch, and I noticed it was using one of the "High Memory" EC2 instances, which is a waste of resources. We should use ACI agents instead as long as there are no issues.
> Use ACI agents to run CI builds

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Subsumes https://github.com/jenkinsci/script-security-plugin/pull/309 and adds every remaining `String`-related signature other than `String.intern`, which while not necessarily unsafe, seems a bit questionable.
> Allow some additional String and Base64 related methods

- pom.xml
This increases the pulled in version of error_prone_annotations
It is required for solving upper bounds issues:
https://github.com/jenkinsci/bom/pull/322
https://github.com/ben-manes/caffeine/blob/fe0131bb4d6dbfca5db4bbb7a06f5b14b92b4ca2/gradle/dependencies.gradle#L39
https://github.com/ben-manes/caffeine/blob/fe0131bb4d6dbfca5db4bbb7a06f5b14b92b4ca2/gradle/dependencies.gradle#L114
Maybe it should be a library plugin, but this should solve it for now,
@dwnusbaum @jglick
> Bump caffeine version - required for bom

- .github/dependabot.yml
- pom.xml
See #331 and https://github.com/ben-manes/caffeine/releases/tag/v3.0.0.
We cannot update `caffeine` to 3.0.0 until a version of Jenkins that requires Java 11 is released and we are ready to update the minimum supported Jenkins version here in `script-security` to that version.
Maybe it would be make sense to try to replace the `caffeine` dependency with a small API on top of `ConcurrentHashMap` or similar if we are not going to be able to update the dependency for a long time. Personally, I am not as concerned about the performance of the caching layer (at least as long as the performance is not terrible) as I am about its correctness, so from my PoV the main benefit of switching to `caffeine` in #160 was that we could avoid the concurrency-related issues we were occasionally seeing with …
> Configure Dependabot to ignore Caffeine 3.x due to Java 11 requirement

- Jenkinsfile
- pom.xml
Updating the minimum core version of this plugin to 2.222.4 allows us to test against the current version of JCasC. 2.222.4 is a fairly conservative choice: http://stats.jenkins.io/pluginversions/script-security.html indicates that 95% of users who are running `script-security` 1.75 (there are no stats yet for 1.76) are already running Jenkins 2.222.4 or newer.
Closes #333.
> Update minimum required core version to 2.222.4 and update JCasC dependency

- .github/dependabot.yml
"If you want to define a range, use the standard pattern for the package manager" 
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore
So, we have to use maven version ranges in this case.
> Update dependabot ignore

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This would whitelist the following signatures:
- staticMethod groovy.xml.XmlUtil escapeXml java.lang.String
- staticField java.util.concurrent.TimeUnit MILLISECONDS
- staticField java.util.concurrent.TimeUnit SECONDS
- new java.util.TreeMap
All of these signatures are utility classes and hence, it should be safe to whitelist them.
> JENKINS-64057: Whitelist XmlUtil and a few java.util scripts

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
See jenkinsci/bom#552. While trying to add Lockable Resources to the BOM, I started tripping on this test. The test assumes there is one `._script` element in the form, but when Lockable Resources is present there is another one earlier on the page for Lockable Resources. The test finds that one instead (it's looking for the first one) and then goes off the rails. Instead I'm having the test pick the last one rather than the first one, which in this case is the one that it's looking for. This gets the test to pass both with and without Lockable Resources present.
> Make `SecureGroovyScriptTest` work in PCT with Lockable Resources

- Jenkinsfile
So long as we test on Linux & Windows, and 8 & 11, I think we are OK. Also `javaLevel` is deprecated.
> Simplify CI matrix

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/RejectedAccessException.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AnnotatedWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/Language.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
> EOL JSR 305

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
https://github.com/jenkinsci/script-security-plugin/pull/365#discussion_r780315118
> Enforce use of `Outer$Inner` syntax in whitelists

- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
Its location has been changed in Guava 14 meaning the tests of this plugin work fine with current baseline but fail with the PCT on the upcoming lts or when baseline is updated.
I could also wait for `2.332.1` to be released and then change the baseline and update the related Guava code, but I believe is simpler to just get rid of the related Guava usage in the test given how simple it is.
*This does not affect production code* but breaks any pipeline trying to run the PCT or the tests of this plugin with newer core versions
> Do not use Guava's `NullOutputStream`

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
See [JENKINS-68070](https://issues.jenkins.io/browse/JENKINS-68070).
Java 15 added a new `CharSequence.isEmpty` default method. This breaks `StaticWhitelistTest` when running against Java 15+ because `String.isEmpty` becomes an override. It would also cause `RejectedAccessException` to be thrown for any sandboxed code that currently calls `String.isEmpty`.
This PR preemptively adds `CharSequence.isEmpty` to `generic-whitelist` so that everything should regardless of what Java version is being used.
I have not actually tested this against Java 15+ myself, so marking the PR as a draft.
> [JENKINS-68070] Adapt generic-whitelist to Java standard library changes in Java 15+

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/JcascTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest/upgradeSmokes/scriptApproval.xml
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test.yaml
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test_expected.yaml
Adds the ability to manage approved script hashes with JCasC. With the current UX to determine the hash you can either approve it and see what was added to the scriptApproval.xml file on disk or compute the SHA-1 of the script. There is an open effort to approve the UX with [JENKINS-62448](https://issues.jenkins.io/browse/JENKINS-62448) https://github.com/jenkinsci/script-security-plugin/pull/300.
Example:
Script:
`println(jenkins.model.Jenkins.instance.getLabels())`
```
security:
scriptApproval:
approvedScriptHashes:
- fccae58c5762bdd15daca97318e9d74333203106 -- print all labels
```
See [JENKINS-62708](https://issues.jenkins.io/browse/JENKINS-62708)
> [JENKINS-62708] Add JCasC support for approved script hashes

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
While `size()` is whitelisted already, `isEmpty()` isn't.
-------------
> Whitelist net.sf.json.JSON isEmpty()

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
Optimize the display of ScriptApproval page.
The textarea actual display is dislocation.
After fix with br element.
> Optimize the display of ScriptApproval page

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
https://github.com/jenkinsci/workflow-cps-plugin/pull/543#discussion_r880583396
> [JENKINS-63766] Work around JDK-8231454

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
`stripIndent` eclipses the `DefaultGroovyMethods` which is already in the generic-whitelist.
Scripts already using this method were breaking when the JVM was upstepped as it would choose standard implementation over the one provided by groovy.
Looking at git history it is not clear to me if you require a jira ticket.  If so let me know the I create one.
> Adapt generic-whitelist to handle addition of String#stripIndent method in Java 15

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
See [JENKINS-69899](https://issues.jenkins.io/browse/JENKINS-69899) and https://github.com/jenkinsci/groovy-sandbox/pull/94.
> [JENKINS-69899] Do not visit EmptyExpression when transforming fields declared using @Field

- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/HasherScriptApprovalTest.java
Fixing test failure introduced in 65867aa471265a16198b92fb439782ba3554da66 when the Maven local repository path contains non-URL-safe characters.
> Never try to treat `URL.path` as a file path

- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/HasherScriptApprovalTest.java
> Never try to treat `URL.path` as a file path (backport)

- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
Applies the change from https://github.com/jenkinsci/workflow-cps-plugin/pull/600 to the copypasta in this plugin.
> Workaround for JDK-8231454 on Java 11 is no longer necessary as of 11.0.17

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
See [JENKINS-42214](https://issues.jenkins-ci.org/browse/JENKINS-42214). Fixing the issue going forward is easy enough, but I need to check the upgrade behavior for existing field signatures in their `scriptApproval.xml` that would be considered invalid after this change.
> [JENKINS-42214] SandboxInterceptor must account for static members being accessed via objects instead of class references

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
Jenkins >= 2.222 should use `ADMINISTER` instead of `RUN_SCRIPTS`.
--------------------------------
> Replace deprecated RUN_SCRIPTS with ADMINISTER permission

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
Jenkins baseline is > 2.226 already.
-----------------------------------------
> Override getCategory() instead of getCategoryName()

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
When I staged SECURITY-3016, I didn't realize that the 1175.x branch in the public repo had been updated in https://github.com/jenkinsci/script-security-plugin/pull/466, so the security fix doesn't include that PR (test only, so no big deal) and we need to merge the two histories.
> Integrate SECURITY-3016 into 1175.x

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript/JENKINS-15604.js
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), loaded the script approval page in the UI, and …
> Replace Prototype.js with native JavaScript

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
Resolves: https://issues.jenkins.io/browse/JENKINS-72264
There is no need for test it because this is very simple issue - just adding missing BR tag between 271 and 272 lines - according to https://issues.jenkins.io/browse/JENKINS-72264 -> description and last comment of @MarkEWaite.
> Add break tag in ScriptSecurity plugin page

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
#468 was incorrect; we would never want to try to serialize this `Thread` in `scriptApproval.xml`! Also best to null it out when complete.
> `convertDeprecatedApprovedClasspathEntriesThread` should be `transient`

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoader.java
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /usr/share/apache-maven-3.9.5
Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /opt/jdk-21
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.197-186.748.amzn2.x86_64", arch: "amd64", family: "unix"
See [JENKINS-72325](https://issues.jenkins.io/browse/JENKINS-72325). Run a `jenkinsci/bom` job with the following patch:
```groovy
diff --git a/Jenkinsfile b/Jenkinsfile
index 2f2ff395..6e8b5e29 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -6,10 +6,6 @@ if (BRANCH_NAME == 'master' && currentBuild.buildCauses*._class == ['jenkins.bra
}
def mavenEnv(Map params = [:], Closure body) {
-  def attempt = 0
-  def attempts = 6
-  retry(count: attempts, conditions: …
```
> [JENKINS-72325] Define an executor and scheduler for `SandboxResolvingClassLoader`

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
I recently went through some additions on our jenkins I think are safe to whitelist in general.
* Added `toFloat` and `toInteger`
All tests locally pass
```[tasklist]
```
> Added `toFloat` and `toInteger` to whitelist

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/HasherScriptApprovalTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
- src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest/reload/scriptApproval.xml
This makes the `load()` method work properly when called after startup, in case of a reload configuration from disk for example.
Functionally, the `reconfigure()` method needs to be called implicitly when calling `load()`, because it updates a snapshot state that is used by running builds. If the persisted state has changed on disk then loaded, the snapshot needs to be updated accordingly.
Without this patch, the `ScriptApproval` state is correct, but anything that has changed since last time it was loaded is not reflected on running builds.
```[tasklist]
```
> Fix reloading configuration from disk

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLoadingTest.java
Still problems with #549, due to an apparent core bug. One of many reasons I dislike `GuiceFinder`. https://github.com/jenkinsci/acceptance-test-harness/pull/1463#issuecomment-1875994033
> `ExtensionList` error after dynamic load

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLoadingTest.java
https://github.com/jenkinsci/bom/issues/2805, amending #552. At least when `jth.jenkins-war.path` is defined (unnecessary for @cloudbees PCT which does not use this flag).
> Skip `ScriptApprovalLoadingTest` in PCT

- Jenkinsfile
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
https://github.com/jenkinsci/script-security-plugin/pull/549#discussion_r1439742106 apparently can cause a functional test flake in CloudBees CI where a signature is approved and then two builds requiring that signature are started nearly simultaneously; sometimes one of them misses the update. Was trying to avoid a lock here but I do not see how.
> Avoid race condition in `ApprovedWhitelist` reconfiguration

- pom.xml
- Asking to bump JTH version to a newer version. 
- Facing issues on testing `ScriptApprovalLoadingTest.dynamicLoading` under IPv6 I faced the following issue:
```
java.io.IOException: Jenkins process terminated prematurely with exit code 1
at org.jvnet.hudson.test.RealJenkinsRule.startJenkins(RealJenkinsRule.java:777)
at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:658)
at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:651)
at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApprovalLoadingTest.dynamicLoading(ScriptApprovalLoadingTest.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jvnet.hudson.test.RealJenkinsRule$1.evaluate(RealJenkinsRule.java:487)
[...]
Caused by: java.io.IOException: Failed to bind to /127.0.0.1:0 …
```
> Bump plugin parent pom to 4.78

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
This change is similar to [instant parse change](https://stackoverflow.com/questions/49028088/scripts-not-permitted-to-use-staticmethod-java-time-instant-parse-java-lang-char) the reasoning, we have the static fields of DateTimeFormatter that was added in [subset of the Java 8 time API](https://github.com/jenkinsci/script-security-plugin/pull/209), but we cannot use the class, because it is not whitelisted to the instance methods.
java.time package, is a safe API that use immutable classes, so it should be safe to use it.
> white list java.time.format.DateTimeFormatter parse method

- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
When playing with these options recently I had some trouble keeping track which does what, so add some Javadoc.
Had IntelliJ IDEA render the Javadoc and it looked fine.
> Add Javadoc for system property escape hatches

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
adding whitelisting for String.replaceAll(pattern, String) 
```[tasklist]
```
> whitelist replaceAll(pattern, String)

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Also add `DateTimeFormatter` `ofPattern` with Locale because with changes of Java 17 some locale now have a 4-digit month name, and we encountered problems with other tools. Some Background: [SO septembers-short-form-sep-no-longer-parses-in-java-17-in-en-gb-locale](https://stackoverflow.com/questions/69267710/septembers-short-form-sep-no-longer-parses-in-java-17-in-en-gb-locale)
Just providing another locale than our default resolves the issue.
None, just added this to the whitelist as it was added in our test instance.
> Also add `DateTimeFormatter` `ofPattern` with `Locale`-parameter to the whitelist

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
* Soft downstream of https://github.com/jenkinsci/jenkins/pull/9674
> Whitelist method moved from `Run#getFullDisplayName` to `HistoricalBuild#getFullDisplayName`

- pom.xml
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
The JenkinsWhitelistTest will fail because
method hudson.model.Run getFullDisplayName does not exist (or is an override)
Uses the same technique as was used in:
* #576
Downstream of:
* https://github.com/jenkinsci/jenkins/pull/9674
Confirmed that the test fails when run with Jenkins incremental.  Failure is also visible in plugin BOM at https://github.com/jenkinsci/bom/pull/3574
* Shows the test failure on ci.jenkins.io as [build 1](https://ci.jenkins.io/job/Plugins/job/script-security-plugin/job/PR-578/1/testReport/).
* Shows the fix passes the test failure on ci.jenkins.io as [build 2](https://ci.jenkins.io/job/Plugins/job/script-security-plugin/job/PR-578/2).
* Shows the fix passes on older versions of Jenkins core in [build 3](https://ci.jenkins.io/job/Plugins/job/script-security-plugi …
> Fix JenkinsWhitelistTest on 2.477 incremental

- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/deprecated-approvedClasspaths-clear-btn-hide.js
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/deprecated-approvedClasspaths-clear-btn-show.js
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/script-approval.js
Use the CSP-compliant `<st:bind>` as in https://github.com/jenkinsci/warnings-ng-plugin/pull/1859 and extract event handlers to a separate JavaScript adjunct.
Regression testing (ATH): https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1781/4/
Regression testing (PCT): https://ci.jenkins.io/job/Tools/job/bom/job/PR-3734/4/
Verified in https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1749/11/ and https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1743/18/ that this resolves the following ATH failures when running in CSP mode (both report-only, and full CSP mode):
- `plugins.GroovyPluginTest#run_system_groovy_from_file`
- `plugins.JobDslPluginTest#should_use_grooy_sandbox_no_whitelisted_content`
- …
> [JENKINS-69651] CSP compatibility for `ScriptApproval`

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
- src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
[JENKINS-73941](https://issues.jenkins.io/browse/JENKINS-73941) - Option to hide "Use Groovy Sandbox" for users without Administer permission globally in the system
Related to 
- https://github.com/jenkinsci/script-security-plugin/pull/584
- https://github.com/jenkinsci/workflow-cps-plugin/pull/948
In https://github.com/jenkinsci/script-security-plugin/pull/584 we implemented the new forceSandbox logic in the Script Security Plugin instead of the Workflow-CPS Plugin.
The specific SandBox implementations are managed in the specific plugins, and in WorkflowCPS there are some functionalities not properly migrated in the previous PR to this repo
When the ForceSandbox option is enabled in the system:
- In WorkFlow-CPS, when a preexistent Pipeline has the sandBox disabled, a nonAdmin user can't …
> JENKINS-73941 - ForceSandbox - Align Script-Security plugin with preexisting behavior in Workflow-CPS plugin

- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
- src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
[JENKINS-73941 -  - Option to hide "Use Groovy Sandbox" for users without Administer permission globally in the system](https://issues.jenkins.io/browse/JENKINS-73941)
Complements:
https://github.com/jenkinsci/script-security-plugin/pull/584
https://github.com/jenkinsci/script-security-plugin/pull/585
After releasing https://github.com/jenkinsci/workflow-cps-plugin/pull/948 we have realized that some logic can be unified between Script-Security and Workflow-CPS plugin.
To do so, we have created the new static methods:
* org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval#shouldHideSandbox
* org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval#validateSandbox
This PR does not include any new functionality, but decrease the techDebt maintaining both, Script-Security and …
> JENKINS-73941 - ForceSandbox - Unify logic in Script-Security for reducing techDebt

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
- src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
Migrate from deprecated EE 8 functionality to non-deprecated EE 9 equivalents.
`mvn clean verify`
> Migrate from EE 8 to EE 9
